server:
  port: 8083

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: "<email>"
    password: "<password>"
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  thymeleaf:
    enable: true
send:
  email:
    from: "<email>"
    nameFrom: "Javanauta"